### ISSUE TITLE
Ask for integration

### ISSUE THREAD

**Issue by flashultra** [cbatson/hxBitcoin#4]
Hi Chuck!
 I saw your library hxBitcoin when I was looking for BigInteger type for Haxe and I did some test against other BigInteger implementation.
 Your library is the best one from the performance stand point. It's faster either from native Java implementation too!

 Incredible work!

 I want to add your BigInt implementation in Haxe standart library, but Haxe use MIT license . Your library is licensed under the custom license .

 Would it be possible for me to suggest your BigInt code under the Haxe MIT license ( standart one use for all Haxe code) ?

 If you agree, I can push a commit from my account or If you want, I can prepeare commit and send to you , so you can suggest a  commit under your account (so your name will be as committer).

 As I say, your implementation is supperior and I think BigInteger class will boost our small Haxe ecosystem. 

Thank you.

**Comment by cbatson** [comment]
Hello there! By all means, I'm happy to relicense so it can be included in
Haxe std lib. I have little bandwidth at this time, so please go ahead and
issue a pull request or commit to make it happen. I will happily approve if
needed. Also, I may be without internet connectivity for the next few days,
so if I am slow to respond to emails or approve the commit, I'll apologize
in advance. Cheers!

Best wishes,
Chuck

**Comment by flashultra** [comment]
Thank you very much Chuck !
Really appreciate your approve to relicense BigInt integration in Haxe Std.
I will update you for the status after creating a pull request. 

Thank you again.

**Comment by flashultra** [comment]
Hi Chuck!
 I want to inform you that I created a pull request https://github.com/HaxeFoundation/haxe/pull/10750 with your implementation.
 Thank you so much again !
 I saw you have some very good implementation of many crypto functions . Would be possible to use and relicense those functions in Haxe crypto lib via a Haxe MIT license ?

**Comment by flashultra** [comment]
@cbatson 
I finished the PR. It was really very easy to work with your code !
In summary, I did some fixes for Python and add new methods pow, modPow, isPrime . Unfortunately my modPow implementation is very  slow, but it works.

I want to thank you again for your contribution. You have done a tremendous amount of work and I am sure many people will benefit from it after the PR merge

I'm thinking of adding some of yours crypto/elliptic methods to the Haxe crypto lib ( https://github.com/haxefoundation/crypto ).

Could you confirm that I have your permission to do so and relicense it under the MIT licence ?

**Comment by cbatson** [comment]
Hello @flashultra. Thank you for all your work on https://github.com/HaxeFoundation/haxe/pull/10750 to get the tests passing on other platforms. I have not been paying too close attention to that PR, but please make sure any new methods have sufficient test coverage. I also made a comment on that PR requesting credit as the author if possible.

Regarding the crypto/elliptic work, will it be possible to be credited in the source as the original author? If so then I agree to the inclusion and license change. Thank you.

**Comment by flashultra** [comment]
Hi @cbatson .
 I added tests for all the new methods, which gave me the opportunity to find and fix some edge cases for other Haxe targets.
 
About the credit as the author, I can't speak for the main Haxe repository as I'm not a main contributor there and I don't have  merge rights , but  I do have a such rights for a crypto repository .

I think it would be no problem  to add  you as a author it in the crypto repository , but since it is under the Haxe wing I should ask before do it. So before I start with any work of such  kind of implementation I will let you know

Thank you again for allowing me to contribute you work to Haxe foundation!

**Comment by flashultra** [comment]
Hi @cbatson  !
 I just added credited in the source to you as the original author . Thank you again !
About crypto , could I use same credit in the source to you  as the original author , when implement yours crypto/elliptic work and relicense it under the Haxe MIT license  ?

**Comment by cbatson** [comment]
Yes that is perfect and fine with me. Thank you!
